---
version: '2'
services:
  client:
    image: jeqo/apache-kafka:0.10.1.0
    links:
      - server:kafka
    command: sleep infinity
  server:
    image: jeqo/apache-kafka:0.10.1.1-2.11
    environment:
      ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
    links:
      - zk1
      - zk2
      - zk3
  zk1:
    image: jeqo/apache-kafka-zookeeper:0.10.1.1-2.11
    environment:
      ZOOKEEPER_MYID: 1
    volumes:
      - ./zookeeper:/zookeeper/config
      - ./zk/logs/1:/var/zookeeper
    command: ["bin/zookeeper-server-start.sh", "/zookeeper/config/zookeeper.properties"]
  zk2:
    image: jeqo/apache-kafka-zookeeper:0.10.1.1-2.11
    environment:
      ZOOKEEPER_MYID: 2
    volumes:
      - ./zookeeper:/zookeeper/config
      - ./zk/logs/1:/var/zookeeper
    command: ["bin/zookeeper-server-start.sh", "/zookeeper/config/zookeeper.properties"]
  zk3:
    image: jeqo/apache-kafka-zookeeper:0.10.1.1-2.11
    environment:
      ZOOKEEPER_MYID: 3
    volumes:
      - ./zookeeper:/zookeeper/config
      - ./zk/logs/1:/var/zookeeper
