---
version: '2'
services:
  client:
    image: jeqo/apache-kafka:0.10.1.0
    links:
      - server:kafka
    command: sleep infinity
  server:
    image: jeqo/apache-kafka-server:0.10.1.0_2.11
    ports:
      - 9092:9092
    links:
      - zookeeper
  zookeeper:
    image: jeqo/apache-kafka-zk:0.10.1.0_2.11
    ports:
      - 2181:2181
