---
version: '2'
services:
    kafka:
        image: jeqo/apache-kafka-server:0.10.0.0-jdk8
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        links:
            - zookeeper
    zookeeper:
        image: jeqo/apache-kafka-zookeeper:0.10.0.0-jdk8
        ports:
         - "2181:2181"
