- hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - name: create container
      docker:
        name: tmp-apache-kafka
        image: "{{ base_image }}"
        command: sleep infinity
        state: started

    - add_host:
        name: tmp-apache-kafka
        groups: docker
        ansible_connection: docker

- hosts: tmp-apache-kafka
  connection: docker
  pre_tasks:
    - package:
        name: sudo
        state: latest
  roles:
    - role: jeqo.apache-kafka
      kafka_version: 0.10.0.0
      kafka_scala_version: 2.11

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: docker commit
      command: "docker commit tmp-apache-kafka tmp-apache-kafka"

    - name: docker kill
      command: "docker kill tmp-apache-kafka"

    - name: docker rm
      command: "docker rm tmp-apache-kafka"

- include: build.yml
