- hosts: localhost
  vars:
    kafka_version: 0.10.1.0
    kafka_scala_version: 2.11
  tasks:
    - set_fact:
        image: jeqo/apache-kafka:{{ kafka_version }}-{{ kafka_scala_version }}

    - name: building {{ image }}
      docker_image:
        name: "{{ image }}"
        path: .
        buildargs:
          kafka_version: "{{ kafka_version }}"
          kafka_scala_version: "{{ kafka_scala_version }}"
        force: yes
        nocache: yes
        push: yes
      register: result

    - debug:
        var: result
