- hosts: localhost
  vars:
    kafka_version: 0.10.2.0
    kafka_scala_version: 2.11
    push: no
    nocache: no
  tasks:
    - set_fact:
        base_image: jeqo/apache-kafka-base
        kafka_image: jeqo/apache-kafka:{{ kafka_version }}-{{ kafka_scala_version }}
        zookeeper_image: jeqo/apache-kafka-zookeeper:{{ kafka_version }}-{{ kafka_scala_version }}
        client_image: jeqo/apache-kafka-client:{{ kafka_version }}-{{ kafka_scala_version }}

    - name: building {{ base_image }}
      docker_image:
        name: "{{ base_image }}"
        path: .
        buildargs:
          kafka_version: "{{ kafka_version }}"
          kafka_scala_version: "{{ kafka_scala_version }}"
        force: yes
        nocache: yes
        push: no
      register: result

    - name: building {{ kafka_image }}
      docker_image:
        name: "{{ kafka_image }}"
        path: kafka
        force: yes
        nocache: "{{ nocache }}"
        push: "{{ push }}"
        pull: no
      register: result

    - name: building {{ zookeeper_image }}
      docker_image:
        name: "{{ zookeeper_image }}"
        path: zookeeper
        force: yes
        nocache: "{{ nocache }}"
        push: "{{ push }}"
        pull: no
      register: result

    - debug:
        var: result

    - name: building {{ client_image }}
      docker_image:
        name: "{{ client_image }}"
        path: client
        force: yes
        nocache: "{{ nocache }}"
        push: "{{ push }}"
        pull: no
      register: result

    - debug:
        var: result
