- hosts: localhost
  vars:
    kafka_version: 0.10.1.0
    kafka_scala_version: 2.11
  tasks:
    - set_fact:
        base_image: jeqo/apache-kafka-base
        kafka_image: jeqo/apache-kafka:{{ kafka_version }}-{{ kafka_scala_version }}
        zookeeper_image: jeqo/apache-kafka-zookeeper:{{ kafka_version }}-{{ kafka_scala_version }}

    - name: building {{ base_image }}
      docker_image:
        name: "{{ base_image }}"
        path: .
        buildargs:
          kafka_version: "{{ kafka_version }}"
          kafka_scala_version: "{{ kafka_scala_version }}"
        force: yes
        nocache: yes
        push: no
      register: result

    - name: building {{ kafka_image }}
      docker_image:
        name: "{{ kafka_image }}"
        path: kafka
        force: yes
        nocache: yes
        push: yes
        pull: no
      register: result

    - name: building {{ zookeeper_image }}
      docker_image:
        name: "{{ zookeeper_image }}"
        path: zookeeper
        force: yes
        nocache: yes
        push: yes
        pull: no
      register: result

    - debug:
        var: result
