---
version: '2'
services:
  client:
    image: jeqo/apache-kafka:0.10.1.0
    links:
      - server:kafka
    command: sleep infinity
  server:
    image: jeqo/apache-kafka:0.10.1.1-2.11
    environment:
      ZOOKEEPER_CONNECT: zk1:2818
    links:
      - zk1
  zk1:
    image: jeqo/apache-kafka-zookeeper:0.10.1.1-2.11
    volumes:
      - ./zookeeper:/config
      - ./zk/logs:/var/zookeeper
    command: ["bin/zookeeper-server-start.sh", "/config/zookeeper.properties"]
