---
version: '2'
services:
  client:
    image: jeqo/apache-kafka:0.10.1.0
    links:
      - server:kafka
    command: sleep infinity
  server:
    image: jeqo/apache-kafka:0.10.1.0_2.11
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2818
    links:
      - zookeeper
  zookeeper:
    image: jeqo/apache-zookeeper:3.4.9
    volumes:
      - ./zoo.cfg:/opt/apache-zookeeper/conf/zoo.cfg
      - ./zk/logs:/var/zookeeper
